### ISSUE TITLE
Can this work on Unity ?

### ISSUE THREAD

**Issue by khurshid-alam** [spheras/desktopfolder#229]
Hi, Unity community developer here. As you know Ubuntu 19.04 will use [Nautilus >=3.30](https://community.ubuntu.com/t/nautilus-3-30-status/8907/) which does not have desktop anymore. Unity is deeply integrated with with the desktop and I was this can be used in unity too.

But, it can not draw wallpaper( draws the icons fine) on unity, just a black screen.

In the absence of the nautilus-desktop, unity-settings-daemon [draws](https://bazaar.launchpad.net/~unity-settings-daemon-team/unity-settings-daemon/trunk/view/head:/plugins/background/gsd-background-manager.c) the background. It checks it nautilus is drawing the background or `org.gnome.desktop.background.show-desktop-icons` is true. (And If it works I can make it to check relative desktop-folder gsettings key, but atm, it doesn't work)

I tried to disable the background plugin from unity-settings-daemon, but it didn't help. 

Can you explain why desktop-folder not showing any background ?

I addition to that I want to sync font-settings (interface and document) with gnome gsettings keys. Atm, fonts does not change on unity.

Another thing is change-wallpaper tries to open gnome-control-center which doesn't exist in unity (for unity the command is `unity-control-center appearance`) but I believe this can be patched easily.

------------
To summarize:

1) Under unity it should use appearance panel from unity-control-center

2) Use GDK_WINDOW_TYPE_HINT_DESKTOP for compiz.

3) Make separate desktop launcher for unity and set `OnlyShownIn=Unity `

**Comment by spheras** [comment]
Hello @khurshid-alam. Thank you for the interest in desktop folder. We are trying to make the application the widest compatible with others distribution/window managers, but you know, sometimes is difficult.  In the case of Unity, I have never checked. First, you should confirm the GTK dependencies compatibility, we are working with Gtk+3.22.

If the problem is a black opaque window, probably you will have to touch [css styles](https://github.com/spheras/desktopfolder/blob/master/data/css/Application.css) and see why is not being rendered correctly in Unity .  Probably those styles like this one:

```CSS
.df_folder.df_note.window-frame.df_transparent, .df_folder.df_note.window-frame.df_transparent:backdrop,
.df_folder.df_note.background.df_transparent, .df_folder.df_note.background.df_transparent:backdrop,
.df_folder.df_note.df_transparent .titlebar, .df_folder.df_note.df_transparent .titlebar:backdrop {
    border-color: @noteColorBackgroundTRANSPARENT;
    background-color: @noteColorBackgroundTRANSPARENT;
    border-color: @noteColorBackgroundTRANSPARENT;
}
```

Or perhaps, the problem is different... perhaps the problem is that the window manager is wrapping the panel window with another (opaque) window, I remember the issue #127, in that case, the photo window doesn't have a header, and Ubuntu Budgie Window Manager created a wrapper window. You'll need to check.

All generic improvements to make it more compatible are more than welcome.  Currently, we are working hard in the next version 1.1.0, with huge changes and improvements.  The project was initially focused on elementary OS, and now we are targeting both Elementary and Ubuntu Budgie. If you are interested trying to port the project to unity too, I could try to advise you, doing my best, but I'm currently a bit overloaded :laughing:
